# Generated by Django 5.0.6 on 2024-05-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
    ]
