# Generated by Django 5.0.6 on 2024-05-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_event_place_alter_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Courses/default.jpg', upload_to='Courses'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
    ]
