# Generated by Django 5.0.6 on 2024-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0003_course_image_alter_course_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ANY', 'uncategorized'), ('TCH', 'tech course'), ('LTR', 'literature course'), ('LAN', 'language course'), ('HND', 'craftsman course'), ('ART', 'art course')], default='ANY', max_length=50),
        ),
    ]
