# Generated by Django 5.0.6 on 2024-05-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0006_alter_event_options_event_duration_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Activities.event'),
        ),
    ]
