# Generated by Django 5.0.6 on 2024-05-22 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0008_booking_booking_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('event', 'user', 'booking_time')},
        ),
    ]
