# Generated by Django 5.0.6 on 2024-05-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0009_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
