# Generated by Django 5.0.6 on 2024-05-24 00:35

import Activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0011_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=Activities.models.default_event_time),
        ),
    ]
