# Generated by Django 5.0.6 on 2024-05-24 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0012_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
