# Generated by Django 5.0.6 on 2024-05-24 02:13

import Activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0014_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='Courses/default.jpg', upload_to=Activities.models.course_image_path),
        ),
    ]
