# Generated by Django 5.0.6 on 2024-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0015_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='num_seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
