# Generated by Django 5.0.6 on 2024-06-02 22:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0018_alter_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.AlterField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
