# Generated by Django 5.0.6 on 2024-06-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0019_remove_subscription_email_alter_event_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default_course.jpeg', upload_to=''),
        ),
    ]
