# Generated by Django 5.0.6 on 2024-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0021_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default_course.jpeg', upload_to=''),
        ),
    ]
